import type { Metadata } from "next";
import { Lora, Inter } from "next/font/google";
import "./globals.css";

const loraSans = Lora({
  variable: "--font-lora-sans",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${loraSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
